services:
  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: ${PG_PASS}
      POSTGRES_DB: ${PG_DATABASE}
      
    ports:
      - 5432:5432